version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 3000:80
    volumes:
      - ./build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - api-network
networks:
  api-network:
    external: true